{"level":"error","message":"LOG REFERER YTD undefined ::ffff:127.0.0.1 undefined","timestamp":"10:16:41 AM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"10:16:42 AM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"10:16:42 AM"}
{"level":"error","message":"(node:20748) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Trying to open unclosed connection.","timestamp":"11:36:12 AM"}
{"level":"error","message":"(node:20748) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Trying to open unclosed connection.","timestamp":"11:36:12 AM"}
{"level":"error","message":"(node:20748) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: Trying to open unclosed connection.","timestamp":"11:36:12 AM"}
{"level":"error","message":"(node:20748) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Error: Trying to open unclosed connection.","timestamp":"11:36:12 AM"}
{"level":"error","message":"(node:20748) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): Error: Trying to open unclosed connection.","timestamp":"11:36:12 AM"}
{"level":"error","message":"(node:20748) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): Error: Trying to open unclosed connection.","timestamp":"11:36:12 AM"}
{"level":"error","message":"(node:20748) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 7): Error: Trying to open unclosed connection.","timestamp":"11:36:12 AM"}
{"level":"error","message":"(node:20748) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 8): Error: Trying to open unclosed connection.","timestamp":"11:36:12 AM"}
{"level":"error","message":"(node:20748) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 9): Error: Trying to open unclosed connection.","timestamp":"11:36:12 AM"}
{"level":"error","message":"(node:20748) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 10): Error: Trying to open unclosed connection.","timestamp":"11:36:12 AM"}
{"level":"error","message":"(node:20748) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 11): Error: Trying to open unclosed connection.","timestamp":"11:36:12 AM"}
{"level":"error","message":"(node:20748) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 12): Error: Trying to open unclosed connection.","timestamp":"11:36:12 AM"}
{"level":"error","message":"(node:20748) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 13): Error: Trying to open unclosed connection.","timestamp":"11:36:12 AM"}
{"level":"error","message":"(node:20748) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 14): Error: Trying to open unclosed connection.","timestamp":"11:36:12 AM"}
{"level":"error","message":"(node:20748) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 15): Error: Trying to open unclosed connection.","timestamp":"11:36:12 AM"}
{"level":"error","message":"(node:20748) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 16): Error: Trying to open unclosed connection.","timestamp":"11:36:12 AM"}
{"level":"error","message":"(node:20748) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 17): Error: Trying to open unclosed connection.","timestamp":"11:36:12 AM"}
{"level":"error","message":"(node:20748) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 18): Error: Trying to open unclosed connection.","timestamp":"11:36:12 AM"}
{"level":"error","message":"(node:20748) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 19): Error: Trying to open unclosed connection.","timestamp":"11:36:12 AM"}
{"level":"error","message":"(node:20748) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 20): Error: Trying to open unclosed connection.","timestamp":"11:36:12 AM"}
{"level":"error","message":"(node:20748) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 21): Error: Trying to open unclosed connection.","timestamp":"11:36:12 AM"}
{"level":"error","message":"(node:20748) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 22): Error: Trying to open unclosed connection.","timestamp":"11:36:12 AM"}
{"level":"error","message":"(node:20748) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 23): Error: Trying to open unclosed connection.","timestamp":"11:36:12 AM"}
{"level":"error","message":"(node:20748) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 24): Error: Trying to open unclosed connection.","timestamp":"11:36:12 AM"}
{"level":"error","message":"(node:20748) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 25): Error: Trying to open unclosed connection.","timestamp":"11:36:12 AM"}
{"level":"error","message":"(node:20748) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 26): Error: Trying to open unclosed connection.","timestamp":"11:36:12 AM"}
{"level":"error","message":"(node:20748) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 27): Error: Trying to open unclosed connection.","timestamp":"11:36:12 AM"}
{"level":"error","message":"(node:20748) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 28): Error: Trying to open unclosed connection.","timestamp":"11:36:12 AM"}
{"level":"error","message":"(node:20748) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 29): Error: Trying to open unclosed connection.","timestamp":"11:36:13 AM"}
{"level":"error","message":"(node:20748) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 30): Error: Trying to open unclosed connection.","timestamp":"11:36:13 AM"}
{"level":"error","message":"(node:20748) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 31): Error: Trying to open unclosed connection.","timestamp":"11:36:13 AM"}
{"level":"error","message":"(node:20748) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 32): Error: Trying to open unclosed connection.","timestamp":"11:36:13 AM"}
{"level":"error","message":"(node:20748) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 33): Error: Trying to open unclosed connection.","timestamp":"11:36:13 AM"}
{"level":"error","message":"(node:20748) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 34): Error: Trying to open unclosed connection.","timestamp":"11:36:13 AM"}
{"level":"error","message":"(node:20748) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 35): Error: Trying to open unclosed connection.","timestamp":"11:36:13 AM"}
{"level":"error","message":"(node:20748) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 36): Error: Trying to open unclosed connection.","timestamp":"11:36:13 AM"}
{"level":"error","message":"(node:20748) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 37): Error: Trying to open unclosed connection.","timestamp":"11:36:13 AM"}
{"level":"error","message":"(node:20748) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 38): Error: Trying to open unclosed connection.","timestamp":"11:36:13 AM"}
{"level":"error","message":"(node:20748) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 39): Error: Trying to open unclosed connection.","timestamp":"11:36:13 AM"}
{"level":"error","message":"(node:20748) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 40): Error: Trying to open unclosed connection.","timestamp":"11:36:13 AM"}
{"level":"error","message":"(node:20748) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 41): Error: Trying to open unclosed connection.","timestamp":"11:36:13 AM"}
{"level":"error","message":"(node:20748) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 42): Error: Trying to open unclosed connection.","timestamp":"11:36:13 AM"}
{"level":"error","message":"(node:20748) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 43): Error: Trying to open unclosed connection.","timestamp":"11:36:13 AM"}
{"level":"error","message":"(node:20748) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 44): Error: Trying to open unclosed connection.","timestamp":"11:36:13 AM"}
{"level":"error","message":"(node:20748) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 45): Error: Trying to open unclosed connection.","timestamp":"11:36:13 AM"}
{"level":"error","message":"(node:20748) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 46): Error: Trying to open unclosed connection.","timestamp":"11:36:13 AM"}
{"level":"error","message":"(node:20748) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 47): Error: Trying to open unclosed connection.","timestamp":"11:36:13 AM"}
{"level":"error","message":"(node:20748) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 48): Error: Trying to open unclosed connection.","timestamp":"11:36:13 AM"}
{"level":"error","message":"(node:20748) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 49): Error: Trying to open unclosed connection.","timestamp":"11:36:13 AM"}
{"level":"error","message":"(node:20748) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 50): Error: Trying to open unclosed connection.","timestamp":"11:36:13 AM"}
{"level":"error","message":"(node:20748) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 51): Error: Trying to open unclosed connection.","timestamp":"11:36:13 AM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"11:36:24 AM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"11:36:24 AM"}
{"level":"error","message":"(node:3400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Trying to open unclosed connection.","timestamp":"11:49:43 AM"}
{"level":"error","message":"(node:3400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Trying to open unclosed connection.","timestamp":"11:49:43 AM"}
{"level":"error","message":"(node:3400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: Trying to open unclosed connection.","timestamp":"11:49:43 AM"}
{"level":"error","message":"(node:3400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Error: Trying to open unclosed connection.","timestamp":"11:49:43 AM"}
{"level":"error","message":"(node:3400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): Error: Trying to open unclosed connection.","timestamp":"11:49:43 AM"}
{"level":"error","message":"(node:3400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): Error: Trying to open unclosed connection.","timestamp":"11:49:43 AM"}
{"level":"error","message":"(node:3400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 7): Error: Trying to open unclosed connection.","timestamp":"11:49:43 AM"}
{"level":"error","message":"(node:3400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 8): Error: Trying to open unclosed connection.","timestamp":"11:49:43 AM"}
{"level":"error","message":"(node:3400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 9): Error: Trying to open unclosed connection.","timestamp":"11:49:43 AM"}
{"level":"error","message":"(node:3400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 10): Error: Trying to open unclosed connection.","timestamp":"11:49:43 AM"}
{"level":"error","message":"(node:3400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 11): Error: Trying to open unclosed connection.","timestamp":"11:49:43 AM"}
{"level":"error","message":"(node:3400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 12): Error: Trying to open unclosed connection.","timestamp":"11:49:43 AM"}
{"level":"error","message":"(node:3400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 13): Error: Trying to open unclosed connection.","timestamp":"11:49:43 AM"}
{"level":"error","message":"(node:3400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 14): Error: Trying to open unclosed connection.","timestamp":"11:49:43 AM"}
{"level":"error","message":"(node:3400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 15): Error: Trying to open unclosed connection.","timestamp":"11:49:43 AM"}
{"level":"error","message":"(node:3400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 16): Error: Trying to open unclosed connection.","timestamp":"11:49:43 AM"}
{"level":"error","message":"(node:3400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 17): Error: Trying to open unclosed connection.","timestamp":"11:49:43 AM"}
{"level":"error","message":"(node:3400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 18): Error: Trying to open unclosed connection.","timestamp":"11:49:43 AM"}
{"level":"error","message":"(node:3400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 19): Error: Trying to open unclosed connection.","timestamp":"11:49:43 AM"}
{"level":"error","message":"(node:3400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 20): Error: Trying to open unclosed connection.","timestamp":"11:49:43 AM"}
{"level":"error","message":"(node:3400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 21): Error: Trying to open unclosed connection.","timestamp":"11:49:43 AM"}
{"level":"error","message":"(node:3400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 22): Error: Trying to open unclosed connection.","timestamp":"11:49:43 AM"}
{"level":"error","message":"(node:3400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 23): Error: Trying to open unclosed connection.","timestamp":"11:49:43 AM"}
{"level":"error","message":"(node:3400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 24): Error: Trying to open unclosed connection.","timestamp":"11:49:43 AM"}
{"level":"error","message":"(node:3400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 25): Error: Trying to open unclosed connection.","timestamp":"11:49:43 AM"}
{"level":"error","message":"(node:3400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 26): Error: Trying to open unclosed connection.","timestamp":"11:49:43 AM"}
{"level":"error","message":"(node:3400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 27): Error: Trying to open unclosed connection.","timestamp":"11:49:43 AM"}
{"level":"error","message":"(node:3400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 28): Error: Trying to open unclosed connection.","timestamp":"11:49:43 AM"}
{"level":"error","message":"(node:3400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 29): Error: Trying to open unclosed connection.","timestamp":"11:49:43 AM"}
{"level":"error","message":"(node:3400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 30): Error: Trying to open unclosed connection.","timestamp":"11:49:43 AM"}
{"level":"error","message":"(node:3400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 31): Error: Trying to open unclosed connection.","timestamp":"11:49:43 AM"}
{"level":"error","message":"(node:3400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 32): Error: Trying to open unclosed connection.","timestamp":"11:49:43 AM"}
{"level":"error","message":"(node:3400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 33): Error: Trying to open unclosed connection.","timestamp":"11:49:43 AM"}
{"level":"error","message":"(node:3400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 34): Error: Trying to open unclosed connection.","timestamp":"11:49:43 AM"}
{"level":"error","message":"(node:3400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 35): Error: Trying to open unclosed connection.","timestamp":"11:49:43 AM"}
{"level":"error","message":"(node:3400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 36): Error: Trying to open unclosed connection.","timestamp":"11:49:43 AM"}
{"level":"error","message":"(node:3400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 37): Error: Trying to open unclosed connection.","timestamp":"11:49:43 AM"}
{"level":"error","message":"(node:3400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 38): Error: Trying to open unclosed connection.","timestamp":"11:49:43 AM"}
{"level":"error","message":"(node:3400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 39): Error: Trying to open unclosed connection.","timestamp":"11:49:43 AM"}
{"level":"error","message":"(node:3400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 40): Error: Trying to open unclosed connection.","timestamp":"11:49:43 AM"}
{"level":"error","message":"(node:3400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 41): Error: Trying to open unclosed connection.","timestamp":"11:49:43 AM"}
{"level":"error","message":"(node:3400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 42): Error: Trying to open unclosed connection.","timestamp":"11:49:43 AM"}
{"level":"error","message":"(node:3400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 43): Error: Trying to open unclosed connection.","timestamp":"11:49:43 AM"}
{"level":"error","message":"(node:3400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 44): Error: Trying to open unclosed connection.","timestamp":"11:49:43 AM"}
{"level":"error","message":"(node:3400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 45): Error: Trying to open unclosed connection.","timestamp":"11:49:43 AM"}
{"level":"error","message":"(node:3400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 46): Error: Trying to open unclosed connection.","timestamp":"11:49:43 AM"}
{"level":"error","message":"(node:3400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 47): Error: Trying to open unclosed connection.","timestamp":"11:49:43 AM"}
{"level":"error","message":"(node:3400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 48): Error: Trying to open unclosed connection.","timestamp":"11:49:43 AM"}
{"level":"error","message":"(node:3400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 49): Error: Trying to open unclosed connection.","timestamp":"11:49:43 AM"}
{"level":"error","message":"(node:3400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 50): Error: Trying to open unclosed connection.","timestamp":"11:49:43 AM"}
{"level":"error","message":"(node:3400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 51): Error: Trying to open unclosed connection.","timestamp":"11:49:43 AM"}
{"level":"warn","message":"uncaughtException { MongoError: failed to connect to server [3.109.206.238:27017] on first connect [MongoError: connection 0 to 3.109.206.238:27017 timed out]\n    at Pool.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:328:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:274:12)\n    at Connection.g (events.js:291:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:10)\n    at Socket.g (events.js:291:16)\n    at emitNone (events.js:86:13)\n    at Socket.emit (events.js:185:7)\n    at Socket._onTimeout (net.js:339:8)\n    at ontimeout (timers.js:365:14)\n    at tryOnTimeout (timers.js:237:5)\n    at Timer.listOnTimeout (timers.js:207:5)\n  name: 'MongoError',\n  message: 'failed to connect to server [3.109.206.238:27017] on first connect [MongoError: connection 0 to 3.109.206.238:27017 timed out]' }","timestamp":"11:49:43 AM"}
{"level":"warn","message":"uncaughtException { MongoError: failed to connect to server [3.109.206.238:27017] on first connect [MongoError: connection 1 to 3.109.206.238:27017 timed out]\n    at Pool.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:328:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:274:12)\n    at Connection.g (events.js:291:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:10)\n    at Socket.g (events.js:291:16)\n    at emitNone (events.js:86:13)\n    at Socket.emit (events.js:185:7)\n    at Socket._onTimeout (net.js:339:8)\n    at ontimeout (timers.js:365:14)\n    at tryOnTimeout (timers.js:237:5)\n    at Timer.listOnTimeout (timers.js:207:5)\n  name: 'MongoError',\n  message: 'failed to connect to server [3.109.206.238:27017] on first connect [MongoError: connection 1 to 3.109.206.238:27017 timed out]' }","timestamp":"11:49:43 AM"}
{"level":"warn","message":"uncaughtException { MongoError: failed to connect to server [3.109.206.238:27017] on first connect [MongoError: connection 2 to 3.109.206.238:27017 timed out]\n    at Pool.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:328:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:274:12)\n    at Connection.g (events.js:291:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:10)\n    at Socket.g (events.js:291:16)\n    at emitNone (events.js:86:13)\n    at Socket.emit (events.js:185:7)\n    at Socket._onTimeout (net.js:339:8)\n    at ontimeout (timers.js:365:14)\n    at tryOnTimeout (timers.js:237:5)\n    at Timer.listOnTimeout (timers.js:207:5)\n  name: 'MongoError',\n  message: 'failed to connect to server [3.109.206.238:27017] on first connect [MongoError: connection 2 to 3.109.206.238:27017 timed out]' }","timestamp":"11:49:43 AM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"11:50:05 AM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"11:50:05 AM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"11:50:42 AM"}
{"level":"error","message":"LOG REFERER YTD undefined ::1 undefined","timestamp":"11:51:57 AM"}
{"level":"error","message":"LOG REFERER YTD undefined ::1 undefined","timestamp":"11:53:05 AM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"11:53:15 AM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"11:53:15 AM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"11:53:19 AM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:21:11)\n    at Server.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:319:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:309:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:177:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"1:36:26 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:21:11)\n    at Server.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:319:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:309:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:177:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"1:36:47 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:21:11)\n    at Server.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:319:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:309:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:177:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"1:36:47 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:21:11)\n    at Server.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:319:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:309:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:177:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"1:36:47 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:21:11)\n    at Server.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:319:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:309:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:177:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"1:36:47 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:21:11)\n    at Server.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:319:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:309:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:177:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"1:36:47 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:21:11)\n    at Server.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:319:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:309:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:177:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"1:36:47 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:21:11)\n    at Server.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:319:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:309:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:177:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"1:36:47 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:21:11)\n    at Server.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:319:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:309:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:177:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"1:36:47 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:21:11)\n    at Server.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:319:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:309:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:177:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"1:36:48 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:21:11)\n    at Server.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:319:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:309:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:177:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"1:36:48 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:21:11)\n    at Server.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:319:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:309:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:177:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"1:36:48 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:21:11)\n    at Server.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:319:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:309:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:177:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"1:36:49 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:21:11)\n    at Server.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:319:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:309:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:177:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"1:36:50 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:21:11)\n    at Server.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:319:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:309:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:177:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"1:36:51 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:21:11)\n    at Server.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:319:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:309:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:177:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"1:37:01 PM"}
