{"level":"error","message":"LOG REFERER YTD undefined ::ffff:127.0.0.1 undefined","timestamp":"10:56:51 AM"}
{"level":"error","message":"LOG REFERER YTD undefined ::ffff:127.0.0.1 undefined","timestamp":"10:56:51 AM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"10:56:52 AM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"10:56:58 AM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"10:57:04 AM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"10:57:32 AM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"10:57:36 AM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"10:57:38 AM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"10:57:44 AM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"10:58:57 AM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"10:59:03 AM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"10:59:05 AM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"10:59:47 AM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"10:59:58 AM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"11:00:01 AM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"11:00:04 AM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"11:00:13 AM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"11:11:47 AM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"12:23:57 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"12:24:00 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"12:24:00 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"12:24:00 PM"}
{"level":"error","message":"HorizonSaleSearch { Last_Status: { '$in': [ 'TRANS_SUCCESS_WO_POLICY', 'TRANS_SUCCESS_WITH_POLICY' ] } } { draw: '1',\n  columns: \n   [ { data: 'User_Data_Id',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'Action',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'Modified_On',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'Product_Name',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'Source',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'PB_CRN',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'ERP_CS',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'ERP_ENTRY',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'Premium',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'Brokerage',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'Insurer',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'Customer',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'Agent',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'SubUser',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'Reporting',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'Ss_Id',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'Fba_Id',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'Sub_User_Id',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] } ],\n  order: [ { column: '0', dir: 'asc' } ],\n  start: '0',\n  length: '10',\n  search: { value: '', regex: 'false' },\n  Col_Transaction_Status: '',\n  Col_Name: '',\n  txtCol_Val: '',\n  Group_Status: 'SELL',\n  App_Version: '',\n  Source: '',\n  Product_Id: '',\n  Insurer_Id: '',\n  PB_CRN: '',\n  ss_id: '8067',\n  session_id: 'yFCWn-3oeoMIHGjSeNPGBc0cd3X0znCa',\n  uid: '110560',\n  page_action: 'all_transaction',\n  registration_number: '',\n  transaction_start_date: '',\n  transaction_end_date: '' }","timestamp":"12:24:00 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"12:24:37 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"12:24:38 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"12:25:45 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"12:28:27 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"12:29:08 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"12:29:40 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"12:29:52 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"12:30:03 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"12:30:03 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"12:30:03 PM"}
{"level":"error","message":"HorizonSaleSearch { Last_Status: { '$in': [ 'TRANS_SUCCESS_WO_POLICY', 'TRANS_SUCCESS_WITH_POLICY' ] } } { draw: '1',\n  columns: \n   [ { data: 'User_Data_Id',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'Action',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'Modified_On',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'Product_Name',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'Source',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'PB_CRN',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'ERP_CS',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'ERP_ENTRY',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'Premium',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'Brokerage',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'Insurer',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'Customer',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'Agent',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'SubUser',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'Reporting',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'Ss_Id',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'Fba_Id',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'Sub_User_Id',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] } ],\n  order: [ { column: '0', dir: 'asc' } ],\n  start: '0',\n  length: '10',\n  search: { value: '', regex: 'false' },\n  Col_Transaction_Status: '',\n  Col_Name: '',\n  txtCol_Val: '',\n  Group_Status: 'SELL',\n  App_Version: '',\n  Source: '',\n  Product_Id: '',\n  Insurer_Id: '',\n  PB_CRN: '',\n  ss_id: '8067',\n  session_id: 'yFCWn-3oeoMIHGjSeNPGBc0cd3X0znCa',\n  uid: '110560',\n  page_action: 'all_transaction',\n  registration_number: '',\n  transaction_start_date: '',\n  transaction_end_date: '' }","timestamp":"12:30:03 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"12:30:44 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"12:31:43 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"12:33:09 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"12:40:00 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"12:40:00 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"12:40:00 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"12:40:00 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"12:40:00 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"12:40:00 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"12:40:00 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"12:40:00 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"12:40:00 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"12:40:00 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"12:40:00 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"12:40:00 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"12:40:00 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"12:40:00 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"12:40:00 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"12:40:00 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"12:40:00 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"12:40:00 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"12:40:00 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"12:40:00 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"12:40:00 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"12:40:00 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"12:40:00 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"12:40:00 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"12:40:00 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"12:40:00 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"12:40:00 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"12:40:00 PM"}
{"level":"error","message":"(node:15264) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): MongoError: E11000 duplicate key error collection: lm-api-qa.sync_contacts index: Sync_Contact_Id_1 dup key: { : null }","timestamp":"12:40:00 PM"}
{"level":"error","message":"(node:15264) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): MongoError: Index with name: Posp_Id_1 already exists with different options","timestamp":"12:40:00 PM"}
{"level":"error","message":"LOG REFERER YTD undefined ::ffff:127.0.0.1 undefined","timestamp":"12:40:39 PM"}
{"level":"error","message":"LOG REFERER YTD undefined ::ffff:127.0.0.1 undefined","timestamp":"12:40:39 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"12:40:49 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:22:11)\n    at Server.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:327:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"1:06:17 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:22:11)\n    at Server.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:327:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"1:06:17 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:22:11)\n    at Server.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:327:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"1:06:17 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:22:11)\n    at Server.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:327:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"1:06:17 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:22:11)\n    at Server.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:327:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"1:06:17 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:22:11)\n    at Server.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:327:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"1:06:17 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:22:11)\n    at Server.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:327:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"1:06:18 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:22:11)\n    at Server.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:327:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"1:06:18 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:22:11)\n    at Server.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:327:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"1:06:18 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:22:11)\n    at Server.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:327:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"1:06:18 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:22:11)\n    at Server.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:327:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"1:06:18 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:22:11)\n    at Server.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:327:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"1:06:18 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:22:11)\n    at Server.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:327:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"1:06:18 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:22:11)\n    at Server.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:327:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"1:06:18 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:22:11)\n    at Server.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:327:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"1:06:18 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:22:11)\n    at Server.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:327:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"1:06:18 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:22:11)\n    at Server.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:327:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"1:06:18 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:22:11)\n    at Server.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:327:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"1:06:19 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:22:11)\n    at Server.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:327:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"1:06:19 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:22:11)\n    at Server.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:327:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"1:06:19 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:22:11)\n    at Server.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:327:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"1:06:19 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:22:11)\n    at Server.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:327:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"1:06:19 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:22:11)\n    at Server.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:327:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"1:06:19 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:22:11)\n    at Server.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:327:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"1:06:19 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:22:11)\n    at Server.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:327:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"1:06:19 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:22:11)\n    at Server.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:327:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"1:06:19 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:22:11)\n    at Server.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:327:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"1:06:19 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:22:11)\n    at Server.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:327:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"1:06:19 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"1:24:27 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"1:28:41 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"1:29:36 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"1:29:36 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"1:29:36 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"1:29:36 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"1:29:36 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"1:29:36 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"1:29:36 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"1:29:36 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"1:29:36 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"1:29:36 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"1:29:36 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"1:29:36 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"1:29:36 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"1:29:36 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"1:29:36 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"1:29:36 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"1:29:36 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"1:29:36 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"1:29:36 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"1:29:36 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"1:29:36 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"1:29:36 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"1:29:36 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"1:29:36 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"1:29:36 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"1:29:36 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"1:29:36 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"1:29:36 PM"}
{"level":"error","message":"(node:13932) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): MongoError: E11000 duplicate key error collection: lm-api-qa.sync_contacts index: Sync_Contact_Id_1 dup key: { : null }","timestamp":"1:29:36 PM"}
{"level":"error","message":"(node:13932) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): MongoError: Index with name: Posp_Id_1 already exists with different options","timestamp":"1:29:36 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"1:31:03 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"1:32:15 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"1:44:47 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"1:45:14 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"1:45:14 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"1:45:14 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"1:45:14 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"1:45:14 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"1:45:14 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"1:45:14 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"1:45:14 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"1:45:14 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"1:45:14 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"1:45:14 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"1:45:14 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"1:45:14 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"1:45:14 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"1:45:14 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"1:45:14 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"1:45:14 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"1:45:14 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"1:45:14 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"1:45:14 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"1:45:14 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"1:45:14 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"1:45:14 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"1:45:14 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"1:45:14 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"1:45:14 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"1:45:14 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"1:45:14 PM"}
{"level":"error","message":"(node:12296) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): MongoError: E11000 duplicate key error collection: lm-api-qa.sync_contacts index: Sync_Contact_Id_1 dup key: { : null }","timestamp":"1:45:14 PM"}
{"level":"error","message":"(node:12296) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): MongoError: Index with name: Posp_Id_1 already exists with different options","timestamp":"1:45:14 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"1:45:17 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"2:13:21 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"2:13:24 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"2:13:24 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"2:13:24 PM"}
{"level":"error","message":"HorizonSaleSearch { Last_Status: { '$in': [ 'TRANS_SUCCESS_WO_POLICY', 'TRANS_SUCCESS_WITH_POLICY' ] } } { draw: '1',\n  columns: \n   [ { data: 'User_Data_Id',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'Action',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'Modified_On',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'Product_Name',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'Source',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'PB_CRN',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'ERP_CS',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'ERP_ENTRY',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'Premium',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'Brokerage',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'Insurer',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'Customer',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'Agent',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'SubUser',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'Reporting',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'Ss_Id',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'Fba_Id',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'Sub_User_Id',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] } ],\n  order: [ { column: '0', dir: 'asc' } ],\n  start: '0',\n  length: '10',\n  search: { value: '', regex: 'false' },\n  Col_Transaction_Status: '',\n  Col_Name: '',\n  txtCol_Val: '',\n  Group_Status: 'SELL',\n  App_Version: '',\n  Source: '',\n  Product_Id: '',\n  Insurer_Id: '',\n  PB_CRN: '',\n  ss_id: '8067',\n  session_id: 'LNk4zLFJxTo9VPP8Q6QjKwGRfv3Gv_VF',\n  uid: '110560',\n  page_action: 'all_transaction',\n  registration_number: '',\n  transaction_start_date: '',\n  transaction_end_date: '' }","timestamp":"2:13:28 PM"}
{"level":"error","message":"LOG REFERER YTD undefined ::ffff:127.0.0.1 undefined","timestamp":"2:35:49 PM"}
{"level":"error","message":"LOG REFERER YTD undefined ::ffff:127.0.0.1 undefined","timestamp":"2:35:49 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"2:35:50 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"2:47:40 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"2:49:22 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"2:49:39 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"2:50:08 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"2:50:54 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"2:51:13 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"2:51:26 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"2:52:05 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"2:53:46 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"2:54:05 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"2:55:05 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"2:55:18 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"3:08:40 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"3:15:39 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"3:15:45 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"3:15:50 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:22:11)\n    at Server.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:327:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"3:42:32 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:22:11)\n    at Server.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:327:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"3:42:32 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:22:11)\n    at Server.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:327:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"3:42:32 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:22:11)\n    at Server.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:327:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"3:42:32 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:22:11)\n    at Server.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:327:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"3:42:34 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:22:11)\n    at Server.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:327:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"3:42:34 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:22:11)\n    at Server.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:327:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"3:42:34 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:22:11)\n    at Server.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:327:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"3:42:34 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:22:11)\n    at Server.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:327:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"3:42:34 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:22:11)\n    at Server.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:327:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"3:42:34 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:22:11)\n    at Server.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:327:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"3:42:34 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:22:11)\n    at Server.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:327:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"3:42:34 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:22:11)\n    at Server.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:327:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"3:42:34 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:22:11)\n    at Server.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:327:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"3:42:34 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:22:11)\n    at Server.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:327:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"3:42:34 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:22:11)\n    at Server.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:327:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"3:42:34 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:22:11)\n    at Server.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:327:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"3:42:34 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:22:11)\n    at Server.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:327:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"3:42:34 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:22:11)\n    at Server.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:327:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"3:42:34 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:22:11)\n    at Server.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:327:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"3:42:35 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:22:11)\n    at Server.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:327:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"3:42:35 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:22:11)\n    at Server.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:327:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"3:42:36 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:22:11)\n    at Server.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:327:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"3:42:36 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:22:11)\n    at Server.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:327:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"3:42:37 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:22:11)\n    at Server.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:327:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"3:42:37 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:22:11)\n    at Server.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:327:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"3:42:37 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:22:11)\n    at Server.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:327:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"3:42:39 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:22:11)\n    at Server.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:327:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Suyash Files\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"65.0.176.149:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"3:43:04 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"3:44:36 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"3:44:36 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"3:44:36 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"3:44:36 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"3:44:36 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"3:44:36 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"3:44:36 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"3:44:36 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"3:44:36 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"3:44:36 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"3:44:36 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"3:44:36 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"3:44:36 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"3:44:36 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"3:44:36 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"3:44:36 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"3:44:36 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"3:44:36 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"3:44:36 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"3:44:36 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"3:44:36 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"3:44:36 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"3:44:36 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"3:44:36 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"3:44:36 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"3:44:36 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"3:44:36 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"3:44:36 PM"}
{"level":"error","message":"(node:4936) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): MongoError: E11000 duplicate key error collection: lm-api-qa.sync_contacts index: Sync_Contact_Id_1 dup key: { : null }","timestamp":"3:44:36 PM"}
{"level":"error","message":"(node:4936) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): MongoError: Index with name: Posp_Id_1 already exists with different options","timestamp":"3:44:36 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"4:57:33 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"4:57:33 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"4:57:33 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"4:57:33 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"4:57:33 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"4:57:33 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"4:57:33 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"4:57:33 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"4:57:33 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"4:57:33 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"4:57:33 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"4:57:33 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"4:57:33 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"4:57:33 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"4:57:33 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"4:57:33 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"4:57:33 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"4:57:33 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"4:57:33 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"4:57:33 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"4:57:33 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"4:57:33 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"4:57:33 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"4:57:33 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"4:57:33 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"4:57:33 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"4:57:33 PM"}
{"level":"warn","message":"Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.","timestamp":"4:57:33 PM"}
{"level":"error","message":"(node:7540) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): MongoError: Index with name: Posp_Id_1 already exists with different options","timestamp":"4:57:33 PM"}
{"level":"error","message":"(node:7540) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): MongoError: E11000 duplicate key error collection: lm-api-qa.sync_contacts index: Sync_Contact_Id_1 dup key: { : null }","timestamp":"4:57:33 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"5:05:49 PM"}
{"level":"error","message":"LOG REFERER YTD undefined ::ffff:127.0.0.1 undefined","timestamp":"5:05:53 PM"}
{"level":"error","message":"LOG REFERER YTD undefined ::ffff:127.0.0.1 undefined","timestamp":"5:05:53 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"5:05:54 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"5:05:57 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"5:06:00 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"5:06:00 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"5:06:06 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"5:11:02 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"5:11:02 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"5:11:02 PM"}
{"level":"error","message":"HorizonSaleSearch { Last_Status: { '$in': [ 'TRANS_SUCCESS_WO_POLICY', 'TRANS_SUCCESS_WITH_POLICY' ] } } { draw: '1',\n  columns: \n   [ { data: 'User_Data_Id',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'Action',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'Modified_On',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'Product_Name',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'Source',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'PB_CRN',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'ERP_CS',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'ERP_ENTRY',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'Premium',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'Brokerage',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'Insurer',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'Customer',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'Agent',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'SubUser',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'Reporting',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'Ss_Id',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'Fba_Id',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] },\n     { data: 'Sub_User_Id',\n       name: '',\n       searchable: 'true',\n       orderable: 'true',\n       search: [Object] } ],\n  order: [ { column: '0', dir: 'asc' } ],\n  start: '0',\n  length: '10',\n  search: { value: '', regex: 'false' },\n  Col_Transaction_Status: '',\n  Col_Name: '',\n  txtCol_Val: '',\n  Group_Status: 'SELL',\n  App_Version: '',\n  Source: '',\n  Product_Id: '',\n  Insurer_Id: '',\n  PB_CRN: '',\n  ss_id: '8067',\n  session_id: 'Zkd9kVXpWbV94K_lrvu_G3dnJfS27KPi',\n  uid: '110560',\n  page_action: 'all_transaction',\n  registration_number: '',\n  transaction_start_date: '',\n  transaction_end_date: '' }","timestamp":"5:11:02 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"5:11:03 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"5:11:50 PM"}
{"level":"error","message":"(node:7540) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): MongoError: E11000 duplicate key error collection: lm-api-qa.identitycounters index: field_1_groupingField_1_model_1 dup key: { : \"Email_Event_Id\", : null, : \"Email_Event\" }","timestamp":"5:11:54 PM"}
{"level":"error","message":"DBG NO_CRN Ticket_","timestamp":"5:11:54 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"5:12:04 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"5:12:10 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"5:12:12 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"5:12:15 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:3000/ticketing/HEPR8527/8067_file_11.jpeg ::1 string","timestamp":"5:12:15 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"5:15:07 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:3000/ticketing/HEPR8527/8067_file_11.jpeg ::1 string","timestamp":"5:15:07 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"5:55:16 PM"}
{"level":"error","message":"DBG NO_CRN Quotation","timestamp":"5:55:19 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"5:55:36 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"5:55:39 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:7000/ ::1 string","timestamp":"6:03:52 PM"}
{"level":"error","message":"LOG REFERER YTD http://localhost:3000/ticketing/CAQU8529/8067_file_11.jpeg ::1 string","timestamp":"6:03:52 PM"}
